build_rpm: Do not check for git-archive
All git binaries have been merged, so we shouldn't check for them.

Signed-off-by: Hannes Reinecke <hare@suse.de>

diff --git a/build_rpm b/build_rpm
--- a/build_rpm
+++ b/build_rpm
@@ -36,8 +36,8 @@ done
 
 VERSION=$(sed -n 's/Version: *\(.*\)/\1/p' mkinitrd.spec)
 
-if ! which git-archive > /dev/null ; then
-    echo "git-archive not found, cannot continue"
+if ! which git > /dev/null ; then
+    echo "git not found, cannot continue"
     exit 1
 fi
 
