- Fix error codes (#115374). - Update changelog.

diff --git a/mkinitrd b/mkinitrd
--- a/mkinitrd
+++ b/mkinitrd
@@ -23,7 +23,7 @@
 # This file is kept in the following CVS repository:
 #
 # $Source: /suse/yast2/cvsroot/mkinitrd/mkinitrd,v $
-# $Revision: 1.124.2.37 $
+# $Revision: 1.124.2.38 $
 
 #
 # Print usage and exit
@@ -428,8 +428,9 @@ add_module() {
 
 # Install a binary file
 cp_bin() {
-    cp -a "$@" \
-    || exit_code=1
+    if ! cp -a "$@" ; then
+	exit_code=1
+    fi
 
     # Remember the binaries installed. We need the list for checking
     # for dynamic libraries.
@@ -1103,7 +1104,9 @@ mkinitrd_kernel() {
     fi
 
     # create an empty initrd
-    mkdir $tmp_mnt || error 1 "could not create temporary directory"
+    if ! mkdir $tmp_mnt ; then
+	error 1 "could not create temporary directory"
+    fi
     dd if=/dev/zero of=$tmp_initrd bs=1k count=$image_blocks 2>/dev/null
     mke2fs -q -F -b 1024 -m 0 -N $image_inodes $tmp_initrd 2>/dev/null 1>&2
     tune2fs -i 0 $tmp_initrd >/dev/null 2>&1
@@ -1147,8 +1150,9 @@ mkinitrd_kernel() {
     if [ $shebang != /bin/sh ]; then
 	ln -s $shebang $tmp_mnt/bin/sh
     fi
-    cp_bin $initrd_insmod $tmp_mnt/sbin/insmod 2>/dev/null \
-	|| error 5 "no static insmod"
+    if ! cp_bin $initrd_insmod $tmp_mnt/sbin/insmod 2>/dev/null ; then
+	error 5 "no static insmod"
+    fi
 
     cp_bin $root_dir/sbin/blkid $tmp_mnt/sbin
 
@@ -2370,8 +2374,10 @@ mkinitrd_kernel() {
     is_mounted_small=1
 
     rmdir $tmp_mnt_small/lost+found
-    cp -a $tmp_mnt/* $tmp_mnt_small \
-	|| error 6 "copy big image to small image failed"
+    if ! cp -a $tmp_mnt/* $tmp_mnt_small ; then
+	error 6 "copy big image to small image failed"
+    fi
+
     chown -R 0:0 $tmp_mnt
 
     umount $tmp_mnt_small
@@ -2467,8 +2473,9 @@ else
 fi
 
 if [ -z "$use_dhcp" ] || [ -z "$use_ipconfig" ]; then
-    [ -z "$rootdev" ] \
-	&& error 1 "No '/' mountpoint specified in $root_dir/etc/fstab"
+    if [ -z "$rootdev" ] ; then
+	error 1 "No '/' mountpoint specified in $root_dir/etc/fstab"
+    fi
 else
     # Not everything is nfs these days.
     case $rootdev in
@@ -2488,8 +2495,9 @@ case "$rootdev" in
 	realrootdev=$(fsck -N "$rootdev" \
 		      | sed -ne '2s/.* \/dev/\/dev/p' \
 		      | sed -e 's/  *//g')
-	[ -z "$realrootdev" ] \
-	    && error 1 "Could not expand $rootdev to real device"
+	if [ -z "$realrootdev" ] ; then
+	    error 1 "Could not expand $rootdev to real device"
+	fi
 	;;
 esac
 
@@ -2579,7 +2587,7 @@ esac
 
 ###################################################################
 
-exit_code=0
+export exit_code=0
 
 initrd_images=( $initrd_images )
 kernel_images=( $kernel_images )
