- Backport bugfixes from 10.2 - Start discovery for iSCSI devices if a target name has been specified on the commandline or retrieved from the iBFT tables (FATE 301555)

diff --git a/mkinitrd b/mkinitrd
--- a/mkinitrd
+++ b/mkinitrd
@@ -23,7 +23,7 @@
 # This file is kept in the following CVS repository:
 #
 # $Source: /suse/yast2/cvsroot/mkinitrd/mkinitrd,v $
-# $Revision: 1.312.2.21 $
+# $Revision: 1.312.2.22 $
 
 usage() {
     cat<<EOF
@@ -359,10 +359,12 @@ auto)
 	791|792) splash_size_1024x768=1 ;;
 	794|795) splash_size_1280x1024=1 ;;
 	*)       vgahex=$(printf 0x%04x "$(($mode))")
-		 size=$(hwinfo --framebuffer | \
-		     sed -ne 's/^.*Mode '$vgahex': \([^ ]\+\) .*$/\1/p' \
-			2>/dev/null)
-		 eval splash_size_$size=1 ;;
+		 if [ -x /usr/sbin/hwinfo ] ; then
+		     size=$(/usr/sbin/hwinfo --framebuffer | \
+			 sed -ne 's/^.*Mode '$vgahex': \([^ ]\+\) .*$/\1/p' \
+			 2>/dev/null)
+		     eval splash_size_$size=1
+		 fi ;;
         esac
     done
     # Get current modes from fb
@@ -874,7 +876,7 @@ check_iscsi_root() {
     local sysfs_path
 
     sysfs_path=$(udevinfo -q path -n $rootdev 2> /dev/null)
-    if [ -z "$sysfs_path" ]; then
+    if [ -z "$sysfs_path" ] || [ ! -d /sys$sysfs_path ] ; then
 	return;
     fi
 
@@ -1205,6 +1207,7 @@ mkinitrd_kernel() {
     local need_mdadm
     local -a features
     local fs_modules drv_modules uld_modules xen_modules
+    local i
 
     tmp_mnt=$work_dir/mnt
     tmp_mnt_small=${tmp_mnt}_small
@@ -1229,6 +1232,14 @@ mkinitrd_kernel() {
 	 ! -d "/lib/modules/$kernel_version/kernel" ]; then
 	oops 2 "No modules found for kernel $kernel_version"
         return
+    fi
+
+    # Make sure to always include the module for the root filesystem
+    # if the root filesystem is modularized.
+    if ! has_module "$rootfstype" && \
+       grep -qe "$rootfstype\.ko:" $modules_dep; then
+	echo "Adding the root filesystem module ($rootfstype)"
+	add_module $rootfstype
     fi
 
     # create an empty initrd
@@ -1326,6 +1337,7 @@ mkinitrd_kernel() {
 
     if has_module iscsi_tcp ; then
 	features=(${features[@]} iscsi)
+	add_module crc32c
 	cp_bin /sbin/iscsid $tmp_mnt/sbin/iscsid
 	cp_bin /sbin/iscsiadm $tmp_mnt/sbin/iscsiadm
 	if [ -x /sbin/fwparam_ibft ] ; then
@@ -1657,25 +1669,31 @@ mkinitrd_kernel() {
 	|    exit \$1
 	|}
 	|
+	|mount -t proc  proc  /proc
+	|mount -t sysfs sysfs /sys
+	|mount -t tmpfs -o mode=0755 udev /dev
+	|
+	|mknod -m 0666 /dev/tty     c 5 0
+	|mknod -m 0600 /dev/console c 5 1
+	|mknod -m 0666 /dev/ptmx    c 5 2
+	|
 	|exec < /dev/console > /dev/console 2>&1
 	|
-	|mount -t tmpfs -o mode=0755 udev /dev
-	|mknod /dev/console c 5 1
-	|mknod /dev/null c 1 3
-	|mknod /dev/kmsg c 1 11
-	|mkdir /dev/pts
+	|mknod -m 0666 /dev/null c 1 3
+	|mknod -m 0600 /dev/kmsg c 1 11
+	|mknod -m 0660 /dev/snapshot c 10 231
+	|mknod -m 0666 /dev/random c 1 8
+	|mknod -m 0644 /dev/urandom c 1 9
+	|mkdir -m 0755 /dev/pts
 	|mkdir -m 1777 /dev/shm
 	|ln -s /proc/self/fd /dev/fd
 	|ln -s fd/0 /dev/stdin
 	|ln -s fd/1 /dev/stdout
 	|ln -s fd/2 /dev/stderr
 	|
-	|mount -tproc proc /proc
-	|mount -tsysfs sysfs /sys
-	|
 	|echo "" > /proc/sys/kernel/hotplug
 	|
-	|kernel_cmdline="\$@"
+	|kernel_cmdline=(\$@)
 	|
 	|# Default timeout is 30 seconds
 	|udev_timeout=30
@@ -1734,6 +1752,12 @@ mkinitrd_kernel() {
 	|	rootdev=\${o#root=}
 	|	rootdev_cmdline=1
 	|	;;
+	|    rootfstype=*)
+	|	rootfstype=\${o#rootfstype=}
+	|	;;
+	|    rootflags=*)
+	|	rootflags=\${o#rootflags=}
+	|	;;
 	|    nfsroot=*)
 	|	rootdev=\${o#nfsroot=}
 	|	rootdev_cmdline=1
@@ -1761,9 +1785,9 @@ mkinitrd_kernel() {
 	|
 	|if [ -z "\$rootdev" ]; then
 	|    rootdev=$rootdev
-	|else
-	|    # lilo strips off the /dev/prefix from device names!
-	|    case \$rootdev in
+	|fi
+	|# lilo strips off the /dev/prefix from device names!
+	|case \$rootdev in
 	|	/dev/disk/by-name/*)
 	|	    rootdevid=\${rootdev#/dev/disk/by-name/}
 	|	    rootdevid=\${rootdevid%-part*}
@@ -1805,12 +1829,11 @@ mkinitrd_kernel() {
 	|	*)
 	|	    rootdev=/dev/\$rootdev
 	|	    ;;
-	|    esac
-	|    md_major=\$(sed -ne 's/\s*\([0-9]\+\)\s*md$/\1/p' /proc/devices)
-	|    if [ -n "\$md_major" -a "\$md_major" = "\$maj" ]; then
-	|        md_minor="\$min"
-	|        md_dev="/dev/md\$md_minor"
-	|    fi
+	|esac
+	|md_major=\$(sed -ne 's/\s*\([0-9]\+\)\s*md$/\1/p' /proc/devices)
+	|if [ -n "\$md_major" -a "\$md_major" = "\$maj" ]; then
+	|    md_minor="\$min"
+	|    md_dev="/dev/md\$md_minor"
 	|fi
 	|
 	|# Verify manual resume mode
@@ -2206,28 +2229,37 @@ mkinitrd_kernel() {
 
     if [ -n "$iscsi_root" ] ; then
 	cat_linuxrc <<-EOF
-	|iscsi_check_ibft {
-	|    if [ -x /sbin/fwparam_ibft ] ; then
-	|        eval \$(/sbin/fwparam_ibft -b 2> /dev/null | sed -ne '/iSCSI_INITIATOR_NAME/p')
-	|        if [ "\$iSCSI_INITIATOR_NAME" ] ; then
-	|            echo "InitiatorName=\$iSCSI_INITIATOR_NAME" > /tmp/initiatorname.iscsi
-	|        fi
+	|# Check of iBFT settings
+	|if [ -x /sbin/fwparam_ibft ] ; then
+	|    eval \$(/sbin/fwparam_ibft -b 2> /dev/null )
+	|    if [ "\$iSCSI_INITIATOR_NAME" ] ; then
+	|        echo "InitiatorName=\$iSCSI_INITIATOR_NAME" > /tmp/initiatorname.iscsi
 	|    fi
-	|}
+	|fi
 	|
 	|for o in \$(cat /proc/cmdline); do
 	|  case \$o in
 	|    TargetAddress=*)
-	|      iscsiserver="\${o#TargetAddress=}" ;;
+	|      if [ "\$o" = "default" ] ; then
+	|          unset iSCSI_TARGET_IPADDR
+	|      else
+	|          iscsiserver="\${o#TargetAddress=}"
+	|      fi ;;
 	|    TargetName=*)
-	|      iscsitarget="\${o#TargetName=}" ;;
+	|      if [ "\$o" = "default" ] ; then
+	|          unset iSCSI_TARGET_NAME
+	|      else
+	|          iscsitarget="\${o#TargetName=}"
+	|      fi ;;
 	|    TargetPort=*)
-	|      iscsiport="\${o#TargetPort=}" ;;
+	|      if [ "\$o" = "default" ] ; then
+	|          unset iSCSI_TARGET_PORT
+	|      else
+	|          iscsiport="\${o#TargetPort=}"
+	|      fi ;;
 	|    InitiatorName=*)
 	|      if [ "\$o" = "default" ] ; then
 	|          rm -f /tmp/initiatorname.iscsi
-	|      elif [ "\$o" = "iBFT" ] ; then
-	|          iscsi_check_ibft
 	|      else
 	|          echo \$o > /tmp/initiatorname.iscsi
 	|      fi ;;
@@ -2241,8 +2273,15 @@ mkinitrd_kernel() {
 	|        mv /tmp/initatorname.iscsi /etc
 	|    fi
 	|fi
-	|# Always enable DHCP for iSCSI
-	|dhcp_mode=1
+	|if [ "\$iSCSI_TARGET_IPADDR" ] ; then
+	|      iscsiserver="\$iSCSI_TARGET_IPADDR"
+	|fi
+	|if [ "\$iSCSI_TARGET_PORT" ] ; then
+	|      iscsiport="\$iSCSI_TARGET_PORT"
+	|fi
+	|if [ "\$iSCSI_TARGET_NAME" ] ; then
+	|      iscsitarget="\$iSCSI_TARGET_NAME"
+	|fi
 	EOF
     fi
 
@@ -2362,6 +2401,14 @@ mkinitrd_kernel() {
 	|/sbin/iscsid
 	|usleep 5000000
 	|
+	|if [ "\$iscsiserver" -a "\$iscsiport" ] ; then
+	|    echo -n "Starting discovery on \${iscsiserver},\${iscsiport}: "
+	|    if /sbin/iscsiadm -m discovery -t st -p \${iscsiserver}:\${iscsiport} 2> /dev/null ; then
+	|        echo "ok."
+	|    else
+	|        echo "failed."
+	|    fi
+	|fi
 	|iscsi_login_root_node
 	|
 	EOF
@@ -2681,7 +2728,7 @@ mkinitrd_kernel() {
 	|    then
 	|	mount -oremount,rw \$2 \$1
 	|	rm -f \$1\$2
-	|	mknod -m 640 \$1\$2 b \$(devmajor \$CURDEV) \$(devminor \$CURDEV)
+	|	mknod -m 0640 \$1\$2 b \$(devmajor \$CURDEV) \$(devminor \$CURDEV)
 	|	mount -oremount,ro \$2 \$1
 	|    fi
 	|    }
@@ -2814,6 +2861,7 @@ mkinitrd_kernel() {
 	|[ "$rootfstype" = "xfs" -a -n "$journaldev" ] && opt="${opt},logdev=$journaldev"
 	|[ "$rootfstype" = "xfs" -a -n "$rootfsflags" ] && opt="${opt},$rootfsflags"
 	|[ "$rootfstype" = "reiserfs" -a -n "$journaldev" ] && opt="${opt},jdev=$journaldev"
+	|[ -n "$rootflags" ] && opt="${opt},$rootflags"
 	|[ -n "$rootfstype" ] && opt="${opt} -t $rootfstype"
 	|if [ -x /bin/nfsmount -a "$rootfstype" = "nfs" ]; then
 	|    nfsmount $rootdev /root || die 1
@@ -2866,11 +2914,11 @@ mkinitrd_kernel() {
 	|
 	|# Create framebuffer devices
 	|if [ -f /proc/fb ]; then
-	|    cat /proc/fb | while read fbnum fbtype; do
+	|    while read fbnum fbtype; do
 	|        if [ $(($fbnum < 32)) ] ; then
-	|            [ -c /dev/fb$fbnum ] || mknod /dev/fb$fbnum c 29 $fbnum
+	|            [ -c /dev/fb$fbnum ] || mknod -m 0660 /dev/fb$fbnum c 29 $fbnum
 	|        fi
-	|    done
+	|    done < /proc/fb
 	|fi
 	|
 	|/bin/mount --move /dev /root/dev
