sbin/mkinitrd: Use $work_dir for all temporary files

diff --git a/sbin/mkinitrd b/sbin/mkinitrd
--- a/sbin/mkinitrd
+++ b/sbin/mkinitrd
@@ -39,9 +39,9 @@ read_options_eval() {
 }
 
 read_options() {
-        egrep -h '%param_' $INITRD_PATH/setup/*.sh | sed 's/^.*_\(.\): \(.*\)$/ tmp_option=\$(read_options_eval \1 \2); [ \"$tmp_option\" ] \&\& cmd_option[\${#cmd_option[@]}]=\"\$tmp_option\"/' > $tmp_dir/$$.params
-        . $tmp_dir/$$.params
-        rm -f $tmp_dir/$$.params
+        egrep -h '%param_' $INITRD_PATH/setup/*.sh /dev/null | sed 's/^.*_\(.\): \(.*\)$/ tmp_option=\$(read_options_eval \1 \2); [ \"$tmp_option\" ] \&\& cmd_option[\${#cmd_option[@]}]=\"\$tmp_option\"/' > $work_dir/params
+        . $work_dir/params
+        rm -f $work_dir/params
 }
 
 parse_option() {
@@ -255,6 +255,13 @@ if [ ! -d "$tmp_dir" ]; then
     exit 1
 fi
 
+work_dir=$(mktemp -qd $tmp_dir/${mkinit_name}.XXXXXX)
+if [ $? -ne 0 ]; then
+        echo "$0: Can't create temp dir, exiting." >&2
+        exit 1
+fi
+
+
 saved_args=$@
 read_options
 while getopts $( cmd_getopts ) a ; do
@@ -362,12 +369,6 @@ PATH=/sbin:/usr/sbin:$PATH
 
 # Fixup old installations
 unset CDPATH
-
-work_dir=$(mktemp -qd $tmp_dir/${mkinit_name}.XXXXXX)
-if [ $? -ne 0 ]; then
-        echo "$0: Can't create temp dir, exiting." >&2
-        exit 1
-fi
 
 umount_proc() {
     [ "$mounted_proc" ] && umount -n $mounted_proc
